# Generated by Django 3.2 on 2023-08-23 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='together_post', to='handover.post'),
        ),
    ]
