# Generated by Django 4.2.4 on 2023-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='연락처')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
            },
        ),
    ]
