# Generated by Django 4.2.4 on 2023-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecommunication', '0002_post_author_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_dt',
            field=models.DateTimeField(verbose_name='CREATE DT'),
        ),
    ]
