# Generated by Django 4.2.4 on 2023-08-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecommunication', '0003_alter_comment_created_at_alter_post_create_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATE DT'),
        ),
    ]
